POST http://localhost:3000/api/task
Accept: application/json
Content-Type: application/json

{       
    "title": "test"
}

###
PUT http://localhost:3000/api/task/19
Accept: application/json
Content-Type: application/json

{       
    "title": "vender",
    "completed": true
}

###
GET http://localhost:3000/api/tasks
Accept: application/json

###
GET http://localhost:3000/api/task/19
Accept: application/json

###
DELETE http://localhost:3000/api/task/21
Accept: application/json
